// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movierequest.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	movierequest.proto

It has these top-level messages:
	PlexMovieRequest
	RequestList
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlexMovieRequest struct {
	Title         string                     `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	RequestType   string                     `protobuf:"bytes,2,opt,name=requestType" json:"requestType,omitempty"`
	Season        string                     `protobuf:"bytes,3,opt,name=season" json:"season,omitempty"`
	Uuid          string                     `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	TimeRequested *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=time_requested,json=timeRequested" json:"time_requested,omitempty"`
}

func (m *PlexMovieRequest) Reset()                    { *m = PlexMovieRequest{} }
func (m *PlexMovieRequest) String() string            { return proto.CompactTextString(m) }
func (*PlexMovieRequest) ProtoMessage()               {}
func (*PlexMovieRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PlexMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PlexMovieRequest) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *PlexMovieRequest) GetSeason() string {
	if m != nil {
		return m.Season
	}
	return ""
}

func (m *PlexMovieRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PlexMovieRequest) GetTimeRequested() *google_protobuf.Timestamp {
	if m != nil {
		return m.TimeRequested
	}
	return nil
}

type RequestList struct {
	Requests []*PlexMovieRequest `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *RequestList) Reset()                    { *m = RequestList{} }
func (m *RequestList) String() string            { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()               {}
func (*RequestList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestList) GetRequests() []*PlexMovieRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*PlexMovieRequest)(nil), "main.PlexMovieRequest")
	proto.RegisterType((*RequestList)(nil), "main.RequestList")
}

func init() { proto.RegisterFile("movierequest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0x26, 0x76, 0x5b, 0x74, 0x82, 0x22, 0x83, 0x94, 0xd0, 0x8b, 0xa1, 0xa7, 0x3d, 0xa5, 0xb0,
	0x3e, 0x41, 0xef, 0x0a, 0x12, 0x7a, 0x97, 0x2d, 0x1d, 0x4b, 0x60, 0xd3, 0xac, 0x4d, 0x22, 0xfa,
	0x68, 0xbe, 0x9d, 0xe4, 0x67, 0x45, 0x7a, 0xcb, 0xf7, 0xcd, 0x7c, 0x3f, 0x19, 0x40, 0xeb, 0x3e,
	0x0d, 0x9d, 0xe9, 0x23, 0x92, 0x0f, 0x6a, 0x3c, 0xbb, 0xe0, 0xb0, 0xb1, 0xbd, 0x39, 0xad, 0x1e,
	0x8f, 0xce, 0x1d, 0x07, 0xda, 0x64, 0x6e, 0x1f, 0xdf, 0x37, 0xc1, 0x58, 0xf2, 0xa1, 0xb7, 0x63,
	0x59, 0x5b, 0xff, 0x30, 0xb8, 0x7f, 0x1d, 0xe8, 0xeb, 0x25, 0x39, 0xe8, 0xe2, 0x80, 0x0f, 0x30,
	0x0f, 0x26, 0x0c, 0x24, 0x98, 0x64, 0xed, 0x8d, 0x2e, 0x00, 0x25, 0xf0, 0x1a, 0xb1, 0xfb, 0x1e,
	0x49, 0x5c, 0xe5, 0xd9, 0x7f, 0x0a, 0x97, 0xb0, 0xf0, 0xd4, 0x7b, 0x77, 0x12, 0xb3, 0x3c, 0xac,
	0x08, 0x11, 0x9a, 0x18, 0xcd, 0x41, 0x34, 0x99, 0xcd, 0x6f, 0xdc, 0xc2, 0x5d, 0xea, 0xf2, 0x56,
	0xf5, 0x74, 0x10, 0x73, 0xc9, 0x5a, 0xde, 0xad, 0x54, 0xa9, 0xac, 0xa6, 0xca, 0x6a, 0x37, 0x55,
	0xd6, 0xb7, 0x49, 0xa1, 0x27, 0xc1, 0x7a, 0x0b, 0xbc, 0x82, 0x67, 0xe3, 0x03, 0x76, 0x70, 0x5d,
	0xcd, 0xbc, 0x60, 0x72, 0xd6, 0xf2, 0x6e, 0xa9, 0xd2, 0x11, 0xd4, 0xe5, 0xff, 0xf4, 0xdf, 0xde,
	0x7e, 0x91, 0x53, 0x9e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x46, 0x24, 0x4b, 0x89, 0x42, 0x01,
	0x00, 0x00,
}
