// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movierequest.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	movierequest.proto

It has these top-level messages:
	PlexMovieRequest
	RequestList
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlexMovieRequest struct {
	Title       string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	RequestType string `protobuf:"bytes,2,opt,name=requestType" json:"requestType,omitempty"`
	Season      string `protobuf:"bytes,3,opt,name=season" json:"season,omitempty"`
}

func (m *PlexMovieRequest) Reset()                    { *m = PlexMovieRequest{} }
func (m *PlexMovieRequest) String() string            { return proto.CompactTextString(m) }
func (*PlexMovieRequest) ProtoMessage()               {}
func (*PlexMovieRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PlexMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PlexMovieRequest) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *PlexMovieRequest) GetSeason() string {
	if m != nil {
		return m.Season
	}
	return ""
}

type RequestList struct {
	Requests []*PlexMovieRequest `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *RequestList) Reset()                    { *m = RequestList{} }
func (m *RequestList) String() string            { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()               {}
func (*RequestList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestList) GetRequests() []*PlexMovieRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*PlexMovieRequest)(nil), "main.PlexMovieRequest")
	proto.RegisterType((*RequestList)(nil), "main.RequestList")
}

func init() { proto.RegisterFile("movierequest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcd, 0x2f, 0xcb,
	0x4c, 0x2d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x4a, 0xe2, 0x12, 0x08, 0xc8, 0x49, 0xad, 0xf0, 0x05, 0xc9, 0x07,
	0x41, 0xe4, 0x85, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x20, 0x1c, 0x21, 0x05, 0x2e, 0x6e, 0xa8, 0x01, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x4c,
	0x60, 0x39, 0x64, 0x21, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0xd4, 0xc4, 0xe2, 0xfc, 0x3c, 0x09, 0x66,
	0xb0, 0x24, 0x94, 0xa7, 0xe4, 0xc8, 0xc5, 0x0d, 0x35, 0xda, 0x27, 0xb3, 0xb8, 0x44, 0xc8, 0x88,
	0x8b, 0x03, 0xaa, 0xab, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x4c, 0x0f, 0xe4, 0x16,
	0x3d, 0x74, 0x87, 0x04, 0xc1, 0xd5, 0x25, 0xb1, 0x81, 0xdd, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xfb, 0xba, 0xc8, 0xa4, 0xc9, 0x00, 0x00, 0x00,
}
